# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amlpipeline.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61mlpipeline.proto\")\n\rAmlJobDetails\x12\x18\n\x10pipelineEndpoint\x18\x01 \x01(\t\"[\n\x10SubmissionStatus\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mlUrl\x18\x02 \x01(\t\x12\r\n\x05runId\x18\x03 \x01(\t\x12\x14\n\x0c\x65rrorMessage\x18\x04 \x01(\t\"\x17\n\x06\x41mlRun\x12\r\n\x05runId\x18\x01 \x01(\t\"\x1f\n\tRunStatus\x12\x12\n\nresultJson\x18\x01 \x01(\t2e\n\x06\x41mlJob\x12\x31\n\x0cSubmitAmlJob\x12\x0e.AmlJobDetails\x1a\x11.SubmissionStatus\x12(\n\x11\x43heckAmlJobStatus\x12\x07.AmlRun\x1a\n.RunStatusB\x0e\xaa\x02\x0bGrpcServiceb\x06proto3')



_AMLJOBDETAILS = DESCRIPTOR.message_types_by_name['AmlJobDetails']
_SUBMISSIONSTATUS = DESCRIPTOR.message_types_by_name['SubmissionStatus']
_AMLRUN = DESCRIPTOR.message_types_by_name['AmlRun']
_RUNSTATUS = DESCRIPTOR.message_types_by_name['RunStatus']
AmlJobDetails = _reflection.GeneratedProtocolMessageType('AmlJobDetails', (_message.Message,), {
  'DESCRIPTOR' : _AMLJOBDETAILS,
  '__module__' : 'amlpipeline_pb2'
  # @@protoc_insertion_point(class_scope:AmlJobDetails)
  })
_sym_db.RegisterMessage(AmlJobDetails)

SubmissionStatus = _reflection.GeneratedProtocolMessageType('SubmissionStatus', (_message.Message,), {
  'DESCRIPTOR' : _SUBMISSIONSTATUS,
  '__module__' : 'amlpipeline_pb2'
  # @@protoc_insertion_point(class_scope:SubmissionStatus)
  })
_sym_db.RegisterMessage(SubmissionStatus)

AmlRun = _reflection.GeneratedProtocolMessageType('AmlRun', (_message.Message,), {
  'DESCRIPTOR' : _AMLRUN,
  '__module__' : 'amlpipeline_pb2'
  # @@protoc_insertion_point(class_scope:AmlRun)
  })
_sym_db.RegisterMessage(AmlRun)

RunStatus = _reflection.GeneratedProtocolMessageType('RunStatus', (_message.Message,), {
  'DESCRIPTOR' : _RUNSTATUS,
  '__module__' : 'amlpipeline_pb2'
  # @@protoc_insertion_point(class_scope:RunStatus)
  })
_sym_db.RegisterMessage(RunStatus)

_AMLJOB = DESCRIPTOR.services_by_name['AmlJob']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\013GrpcService'
  _AMLJOBDETAILS._serialized_start=21
  _AMLJOBDETAILS._serialized_end=62
  _SUBMISSIONSTATUS._serialized_start=64
  _SUBMISSIONSTATUS._serialized_end=155
  _AMLRUN._serialized_start=157
  _AMLRUN._serialized_end=180
  _RUNSTATUS._serialized_start=182
  _RUNSTATUS._serialized_end=213
  _AMLJOB._serialized_start=215
  _AMLJOB._serialized_end=316
# @@protoc_insertion_point(module_scope)
